### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by MordicusEtCubitus** [addok/addok#614]
When running addok tutorial using python 3.8 (https://addok.readthedocs.io/en/latest/tutorial/) I got this issue:

```python
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/dicotopo_geocodage/bin/addok", line 11, in <module>
    load_entry_point('addok==1.0.2', 'console_scripts', 'addok')()
  File "/home/user/anaconda3/envs/dicotopo_geocodage/lib/python3.8/site-packages/addok/bin/__init__.py", line 30, in main
    args.func(args)
  File "addok/batch.py", line 15, in addok.batch.run
  File "addok/batch.py", line 48, in addok.batch.process_file
  File "addok/batch.py", line 69, in addok.batch.batch
  File "/home/user/anaconda3/envs/dicotopo_geocodage/lib/python3.8/site-packages/addok/helpers/__init__.py", line 162, in parallelize
    for chunk in pool.imap_unordered(func, iterable, chunk_size):
  File "/home/user/anaconda3/envs/dicotopo_geocodage/lib/python3.8/site-packages/addok/helpers/__init__.py", line 152, in imap_unordered
    result = IMapUnorderedIterator(self._cache)
  File "/home/user/anaconda3/envs/dicotopo_geocodage/lib/python3.8/multiprocessing/pool.py", line 835, in __init__
    self._cache = pool._cache
AttributeError: '_PoolCache' object has no attribute '_cache'
```

But works well on Python 3.7

Thanks !

**Comment by rdemendoza** [comment]
+1

**Comment by cquest** [comment]
Here a fix I tested in by branch...

https://github.com/addok/addok/commit/e6525676beed8e2b97cdcae37c5413a42eaa4dca

**Comment by ThomasG77** [comment]
Le fix de la branche mentionnée par @cquest en ligne de commande. La 1ère ligne suppose que vous êtes dans un environnement virtuel

```
site_packages=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
sed -i 's#IMapUnorderedIterator(self._cache)#IMapUnorderedIterator(self)#g' "${site_packages}/addok/helpers/__init__.py"
```

**Comment by jdesboeufs** [comment]
Python 3.8-3.11 versions are supported since addok `1.0.2` and `1.1.0`.
